"""adding new table which is user

Revision ID: 043ba689f870
Revises: 2bb19e7f583b
Create Date: 2026-02-18 12:22:07.103579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "043ba689f870"
down_revision: Union[str, Sequence[str], None] = "2bb19e7f583b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "user" not in inspector.get_table_names():
        op.create_table(
            "user",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("email"),
        )

    # SQLite: use batch_alter_table for alter_column (SQLite doesn't support ALTER COLUMN)
    with op.batch_alter_table("asset") as batch_op:
        batch_op.alter_column("ticker", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("amount", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("avg_price", existing_type=sa.FLOAT(), nullable=True)

    # Add user_id first as nullable (for existing rows), then populate & update
    with op.batch_alter_table("portfolio") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Uuid(), nullable=True))
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    # Ensure at least one user exists (for empty user table), then assign to portfolios
    conn.execute(
        sa.text(
            "INSERT OR IGNORE INTO user (id, name, email, password) "
            "VALUES ('00000000-0000-0000-0000-000000000001', 'default', 'default@localhost', '')"
        )
    )
    conn.execute(
        sa.text(
            "UPDATE portfolio SET user_id = (SELECT id FROM user LIMIT 1) WHERE user_id IS NULL"
        )
    )

    with op.batch_alter_table("portfolio") as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.Uuid(), nullable=False)
        batch_op.create_foreign_key("fk_portfolio_user_id", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("portfolio") as batch_op:
        batch_op.drop_constraint("fk_portfolio_user_id", type_="foreignkey")
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("user_id")
    with op.batch_alter_table("asset") as batch_op:
        batch_op.alter_column("ticker", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("amount", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("avg_price", existing_type=sa.FLOAT(), nullable=False)
    op.drop_table("user")
    # ### end Alembic commands ###
